import yfinance as yf
import pandas as pd
from pathlib import Path

OUTPUT_FILE = Path("39-retrograde-market-volatility/sp500_data_1950.csv")

def acquire_data():
    print("Downloading S&P 500 data from 1950...")
    # ^GSPC is the ticker for S&P 500
    sp500 = yf.download("^GSPC", start="1950-01-01", progress=False)
    
    if sp500.empty:
        print("Failed to download data.")
        return

    # Flatten columns if multi-index (yfinance sometimes does this)
    if isinstance(sp500.columns, pd.MultiIndex):
        sp500.columns = sp500.columns.get_level_values(0)

    sp500 = sp500.reset_index()
    
    # Calculate daily returns
    sp500['Return'] = sp500['Close'].pct_change()
    
    # Calculate 30-day rolling volatility (annualized)
    # Volatility = Std Dev of returns * sqrt(252 trading days)
    sp500['Realized_Vol_30d'] = sp500['Return'].rolling(window=30).std() * (252 ** 0.5) * 100
    
    # Drop NaN values generated by rolling window
    sp500 = sp500.dropna()
    
    print(f"Downloaded {len(sp500)} records.")
    print(sp500.head())
    
    sp500.to_csv(OUTPUT_FILE, index=False)
    print(f"Saved to {OUTPUT_FILE}")

if __name__ == "__main__":
    acquire_data()

